apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sefcnet-logs-pvc
  namespace: sefcnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sefcnet-artifacts-pvc
  namespace: sefcnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi